"""Regression data and scenario: one or more steps for every required program.

All input data are synthetic: ``PREPARE_STEPS`` generate them with the Linux
reference build and ``TEXT_INPUTS`` are written by Python, so they can be
redistributed freely. Steps that involve random numbers use fixed seeds.
"""

from pydantic import BaseModel, Field


class Step(BaseModel):
    """One program run."""

    name: str
    program: str
    args: list[str]
    env: dict[str, str] = Field(default_factory=dict)


def _step(name: str, program: str, *args: str, env: dict[str, str] | None = None) -> Step:
    """Build a step.

    Args:
        name: Unique step name; logs are stored under this name.
        program: AFNI program name without extension.
        *args: Program arguments.
        env: Extra environment variables for this step.

    Returns:
        The step.
    """
    return Step(name=name, program=program, args=list(args), env=env or {})


_BLOB = "1000*step(1-((i-{ci})/14)^2-((j-{cj})/16)^2-((k-12)/9)^2)"
_CORE = "+300*step(1-((i-{ci})/6)^2-((j-{cj3})/7)^2-((k-12)/4)^2)"
_ANAT = _BLOB + _CORE + "+40*a"
_EPI = (
    "800*step(1-((i-{ci})/11)^2-((j-16)/12)^2-((k-10)/7)^2)"
    "+25*step(9-(i-10)^2-(j-16)^2-(k-10)^2)*step(mod(l,16)-7.5)"
    "+0.5*l+10*a"
)

TEXT_INPUTS: dict[str, str] = {
    "stim.1D": "16 48 80\n",
    "x.1D": "".join(f"{0.25 * i:g} {1.5 - 0.1 * i:g}\n" for i in range(12)),
    "y.1D": "".join(f"{(i * 7) % 5 - 2}\n" for i in range(12)),
    "undump.txt": "10 10 10 5\n12 11 9 3\n20 20 12 7\n",
}

PREPARE_STEPS: list[Step] = [
    _step(
        "gen_rnd",
        "3dcalc",
        "-a",
        "jRandomDataset:32,32,16,6",
        "-expr",
        "a*100",
        "-datum",
        "float",
        "-prefix",
        "rnd",
    ),
    _step(
        "gen_short",
        "3dcalc",
        "-a",
        "rnd+orig",
        "-expr",
        "a*10",
        "-datum",
        "short",
        "-prefix",
        "rnd_short.nii",
    ),
    _step("gen_niigz", "3dcalc", "-a", "rnd+orig", "-expr", "a", "-prefix", "rnd.nii.gz"),
    _step(
        "gen_gz",
        "3dcalc",
        "-a",
        "rnd+orig",
        "-expr",
        "a",
        "-prefix",
        "rnd_gz",
        env={"AFNI_COMPRESSOR": "GZIP"},
    ),
    _step(
        "gen_anat_sharp",
        "3dcalc",
        "-a",
        "jRandomDataset:40,40,24,1",
        "-expr",
        _ANAT.format(ci=20, cj=20, cj3=23),
        "-datum",
        "float",
        "-prefix",
        "anat_sharp",
    ),
    _step(
        "gen_anat",
        "3dmerge",
        "-1blur_fwhm",
        "3",
        "-datum",
        "short",
        "-prefix",
        "anat",
        "anat_sharp+orig",
    ),
    _step(
        "gen_anat_shift_sharp",
        "3dcalc",
        "-a",
        "jRandomDataset:40,40,24,1",
        "-expr",
        _ANAT.format(ci=21, cj=19, cj3=22),
        "-datum",
        "float",
        "-prefix",
        "anat_shift_sharp",
    ),
    _step(
        "gen_anat_shift",
        "3dmerge",
        "-1blur_fwhm",
        "3",
        "-datum",
        "short",
        "-prefix",
        "anat_shift",
        "anat_shift_sharp+orig",
    ),
    _step(
        "gen_epi",
        "3dcalc",
        "-a",
        "jRandomDataset:32,32,20,48",
        "-expr",
        _EPI.format(ci=16),
        "-datum",
        "float",
        "-prefix",
        "epi_raw",
    ),
    _step("gen_epi_tr", "3dTcat", "-tr", "2", "-prefix", "epi", "epi_raw+orig"),
    _step(
        "gen_motion",
        "3dcalc",
        "-a",
        "epi_raw+orig",
        "-expr",
        _EPI.format(ci="16-step(l-23.5)").replace("+10*a", "+10*a*0"),
        "-datum",
        "float",
        "-prefix",
        "motion_raw",
    ),
    _step("gen_motion_tr", "3dTcat", "-tr", "2", "-prefix", "motion", "motion_raw+orig"),
    _step(
        "gen_mask",
        "3dcalc",
        "-a",
        "anat+orig",
        "-expr",
        "step(a-500)",
        "-datum",
        "byte",
        "-prefix",
        "mask",
    ),
    _step(
        "gen_epimask",
        "3dcalc",
        "-a",
        "epi+orig[0]",
        "-expr",
        "step(a-400)",
        "-datum",
        "byte",
        "-prefix",
        "epimask",
    ),
    _step(
        "gen_roi",
        "3dcalc",
        "-a",
        "epimask+orig",
        "-expr",
        "a*(1+step(i-16)+2*step(j-16))",
        "-datum",
        "short",
        "-prefix",
        "roi",
    ),
    *[
        _step(
            f"gen_subj{n}",
            "3dcalc",
            "-a",
            "jRandomDataset:32,32,20,1",
            "-expr",
            f"20*a+5*step(16-(i-10)^2-(j-16)^2-(k-10)^2)+{n}*sin(i*{n}+j*{2 * n}+k*3)",
            "-datum",
            "float",
            "-prefix",
            f"subj{n}",
        )
        for n in range(1, 15)
    ],
]

_SUBJECTS = [f"subj{n}+orig" for n in range(1, 15)]
_THREADS = {"OMP_NUM_THREADS": "1"}

SCENARIO: list[Step] = [
    _step("info_brik", "3dinfo", "rnd+orig"),
    _step("info_nii", "3dinfo", "rnd_short.nii"),
    _step("info_niigz", "3dinfo", "rnd.nii.gz"),
    _step("info_verb", "3dinfo", "-verb", "rnd+orig"),
    _step("info_n4", "3dinfo", "-n4", "-tr", "-orient", "epi+orig"),
    _step(
        "calc_c1",
        "3dcalc",
        "-a",
        "rnd+orig",
        "-b",
        "rnd.nii.gz",
        "-expr",
        "a*b/100+sqrt(abs(a))",
        "-prefix",
        "c1",
    ),
    _step(
        "calc_c2",
        "3dcalc",
        "-a",
        "rnd+orig",
        "-expr",
        "sin(a)*exp(-abs(a)/50)+log(1+abs(a))",
        "-prefix",
        "c2.nii",
    ),
    _step(
        "calc_c3",
        "3dcalc",
        "-a",
        "rnd_short.nii",
        "-expr",
        "step(a)*a",
        "-datum",
        "short",
        "-prefix",
        "c3.nii.gz",
    ),
    _step("calc_gz_in", "3dcalc", "-a", "rnd_gz+orig", "-expr", "a*2", "-prefix", "c_gzin"),
    _step(
        "calc_gz_out",
        "3dcalc",
        "-a",
        "rnd+orig",
        "-expr",
        "a+1",
        "-prefix",
        "c_gzout",
        env={"AFNI_COMPRESSOR": "GZIP"},
    ),
    _step("calc_spawn", "3dinfo", "-n4", "-max", "3dcalc( -a rnd+orig -expr 2*a -datum float )"),
    _step("tstat_t1", "3dTstat", "-mean", "-stdev", "-max", "-prefix", "t1", "rnd+orig"),
    _step("tstat_t2", "3dTstat", "-median", "-prefix", "t2.nii.gz", "rnd.nii.gz"),
    _step(
        "tstat_epi", "3dTstat", "-mean", "-stdev", "-cvarinv", "-prefix", "tstat_epi", "epi+orig"
    ),
    _step("tcat", "3dTcat", "-prefix", "tcat", "epi+orig[0..9]", "epi+orig[40..$]"),
    _step("bucket", "3dbucket", "-prefix", "bucket", "anat+orig", "mask+orig"),
    _step("copy", "3dcopy", "anat+orig", "copy_anat"),
    _step("refit", "3drefit", "-xorigin", "10", "-zorigin", "-5", "-TR", "2.5", "copy_anat+orig"),
    _step("notes", "3dNotes", "-a", "afni-win regression note", "copy_anat+orig"),
    _step(
        "resample",
        "3dresample",
        "-dxyz",
        "2",
        "2",
        "2",
        "-rmode",
        "Li",
        "-inset",
        "anat+orig",
        "-prefix",
        "resample",
    ),
    _step("afni_to_nifti", "3dAFNItoNIFTI", "-prefix", "anat_afni.nii", "anat+orig"),
    _step(
        "zeropad", "3dZeropad", "-I", "2", "-S", "3", "-A", "1", "-prefix", "zeropad", "anat+orig"
    ),
    _step("automask", "3dAutomask", "-prefix", "automask", "epi+orig"),
    _step("autobox", "3dAutobox", "-prefix", "autobox", "-input", "anat+orig"),
    _step(
        "volreg",
        "3dvolreg",
        "-base",
        "0",
        "-1Dfile",
        "volreg.1D",
        "-prefix",
        "volreg",
        "motion+orig",
        env=_THREADS,
    ),
    _step(
        "allineate",
        "3dAllineate",
        "-base",
        "anat+orig",
        "-source",
        "anat_shift+orig",
        "-prefix",
        "allin",
        "-1Dmatrix_save",
        "allin.aff12.1D",
        "-cost",
        "ls",
        "-warp",
        "shift_rotate",
        env=_THREADS,
    ),
    _step(
        "qwarp",
        "3dQwarp",
        "-base",
        "anat+orig",
        "-source",
        "anat_shift+orig",
        "-prefix",
        "qwarp",
        "-maxlev",
        "1",
        "-blur",
        "0",
        "0",
        "-noweight",
        "-quiet",
        env=_THREADS,
    ),
    _step(
        "nwarp_apply",
        "3dNwarpApply",
        "-nwarp",
        "qwarp_WARP+orig",
        "-source",
        "anat_shift+orig",
        "-prefix",
        "nwarp_apply",
        env=_THREADS,
    ),
    _step(
        "nwarp_cat",
        "3dNwarpCat",
        "-prefix",
        "nwarp_cat",
        "-warp1",
        "qwarp_WARP+orig",
        "-warp2",
        "allin.aff12.1D",
        env=_THREADS,
    ),
    _step("tshift", "3dTshift", "-tpattern", "alt+z", "-prefix", "tshift", "epi+orig"),
    _step(
        "despike", "3dDespike", "-NEW", "-nomask", "-prefix", "despike", "epi+orig", env=_THREADS
    ),
    _step("toutcount", "3dToutcount", "-automask", "epi+orig"),
    _step("tnorm", "3dTnorm", "-prefix", "tnorm", "epi+orig"),
    _step("detrend", "3dDetrend", "-polort", "2", "-prefix", "detrend", "epi+orig"),
    _step("bandpass", "3dBandpass", "-prefix", "bandpass", "0.01", "0.1", "epi+orig", env=_THREADS),
    _step(
        "tproject",
        "3dTproject",
        "-input",
        "epi+orig",
        "-polort",
        "2",
        "-passband",
        "0.01",
        "0.1",
        "-prefix",
        "tproject",
        env=_THREADS,
    ),
    _step(
        "blur_to_fwhm",
        "3dBlurToFWHM",
        "-FWHM",
        "4",
        "-input",
        "epi+orig[0..11]",
        "-mask",
        "epimask+orig",
        "-prefix",
        "blur_to_fwhm",
        env=_THREADS,
    ),
    _step(
        "blur_in_mask",
        "3dBlurInMask",
        "-input",
        "epi+orig",
        "-FWHM",
        "3",
        "-mask",
        "epimask+orig",
        "-prefix",
        "blur_in_mask",
        env=_THREADS,
    ),
    _step("merge", "3dmerge", "-1blur_fwhm", "4", "-doall", "-prefix", "merge", "epi+orig"),
    _step("maskave", "3dmaskave", "-mask", "epimask+orig", "-quiet", "epi+orig"),
    _step(
        "mask_tool",
        "3dmask_tool",
        "-input",
        "mask+orig",
        "-dilate_input",
        "1",
        "-prefix",
        "mask_tool",
    ),
    _step("maskdump", "3dmaskdump", "-mask", "epimask+orig", "-noijk", "tstat_epi+orig"),
    _step("roistats", "3dROIstats", "-mask", "roi+orig", "-nzmean", "epi+orig"),
    _step("brickstat", "3dBrickStat", "-mean", "-max", "-min", "-count", "anat+orig"),
    _step("histog", "3dhistog", "-nbin", "20", "anat+orig"),
    _step("nvals", "3dnvals", "epi+orig"),
    _step(
        "undump",
        "3dUndump",
        "-prefix",
        "undump",
        "-master",
        "anat+orig",
        "-ijk",
        "-datum",
        "short",
        "undump.txt",
    ),
    _step("unifize", "3dUnifize", "-prefix", "unifize", "-input", "anat+orig", env=_THREADS),
    _step(
        "clustsim",
        "3dClustSim",
        "-nxyz",
        "16",
        "16",
        "10",
        "-dxyz",
        "2",
        "2",
        "2",
        "-fwhm",
        "4",
        "-iter",
        "1000",
        "-seed",
        "1234",
        "-prefix",
        "clustsim",
        env=_THREADS,
    ),
    _step(
        "fwhmx",
        "3dFWHMx",
        "-mask",
        "epimask+orig",
        "-input",
        "epi+orig",
        "-acf",
        "fwhmx_acf.1D",
        env=_THREADS,
    ),
    _step(
        "deconvolve",
        "3dDeconvolve",
        "-input",
        "epi+orig",
        "-polort",
        "2",
        "-num_stimts",
        "1",
        "-stim_times",
        "1",
        "stim.1D",
        "BLOCK(16,1)",
        "-stim_label",
        "1",
        "task",
        "-fout",
        "-tout",
        "-x1D",
        "X.xmat.1D",
        "-bucket",
        "decon",
        "-cbucket",
        "decon_cbuck",
        env=_THREADS,
    ),
    _step(
        "remlfit",
        "3dREMLfit",
        "-matrix",
        "X.xmat.1D",
        "-input",
        "epi+orig",
        "-mask",
        "epimask+orig",
        "-Rbuck",
        "reml",
        "-fout",
        "-tout",
        env=_THREADS,
    ),
    _step(
        "synthesize",
        "3dSynthesize",
        "-cbucket",
        "decon_cbuck+orig",
        "-matrix",
        "X.xmat.1D",
        "-select",
        "baseline",
        "-prefix",
        "synth",
    ),
    _step("ttest", "3dttest++", "-setA", *_SUBJECTS, "-prefix", "ttest", env=_THREADS),
    _step(
        "ttest_clustsim",
        "3dttest++",
        "-setA",
        *_SUBJECTS,
        "-mask",
        "epimask+orig",
        "-Clustsim",
        "2",
        "-seed",
        "3217343",
        "1830201",
        "-prefix",
        "ttest_cs",
        "-prefix_clustsim",
        "ttcs",
        env=_THREADS,
    ),
    _step(
        "clust",
        "3dclust",
        "-1Dformat",
        "-nosum",
        "-1dindex",
        "0",
        "-1tindex",
        "1",
        "-2thresh",
        "-2",
        "2",
        "-dxyz=1",
        "1.01",
        "5",
        "ttest+orig",
    ),
    _step("mean", "3dMean", "-prefix", "mean", "subj1+orig", "subj2+orig", "subj3+orig"),
    _step(
        "localstat",
        "3dLocalstat",
        "-nbhd",
        "SPHERE(2)",
        "-stat",
        "mean",
        "-stat",
        "stdev",
        "-prefix",
        "localstat",
        "anat+orig",
        env=_THREADS,
    ),
    _step("deval", "1deval", "-a", "x.1D[0]", "-b", "x.1D[1]", "-expr", "sin(a)+b^2"),
    _step("cat", "1dcat", "x.1D", "y.1D"),
    _step("transpose", "1dtranspose", "x.1D"),
    _step("ccalc", "ccalc", "-expr", "sqrt(2)*PI+exp(1)"),
    _step("cat_matvec", "cat_matvec", "allin.aff12.1D", "-I"),
    _step("attribute", "3dAttribute", "DELTA", "anat+orig"),
    _step("newid", "3dnewid", "-hash", "afni-win"),
]
